### ISSUE TITLE
CSS Bug

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/Wadmin#2]
Depois que adicionei o grunt desconfigurou o CSS.
Não sei exatamente o que é, mas não me apeguei a isso se puder conferir.

**Comment by jackmakiyama** [comment]
achei aqui um problema, o sass no grunt não está concatenando os arquivos.

**Comment by jackmakiyama** [comment]
@FilipeLinhares acho que é isso mesmo, só não sei qual é a melhor opção, concatenar ou fazer um arquivos .scss que inclua todos os outros na ordem correta.

**Comment by filipelinhares** [comment]
@jackmakiyama vou fazer umas modificações aqui e mando um pr.

**Comment by jackmakiyama** [comment]
Ai sim @FilipeLinhares merge feito do PR, obrigado pela contribuição.
Estamos aqui no norte de Mato Grosso nos reeducando, começando com esse projeto.

Eu ainda não sei o que deu no SASS(ou no Grunt) que ele só conseguiu gerar o output quando eu adicionei diretamente o main.scss no input.

Ai sim resolveu o problema do bug.

**Comment by filipelinhares** [comment]
@jackmakiyama eu cometi um erro, você viu que dei import dos Buttons primeiro né? Não percebi seu css resets no arquivo styles.scss. Pra ficar certinho, no arquivo main.scss coloque o import do arquivo styles.scss primeiro pra funcionar os resets.

@import "styles.scss";
os demais imports depois.

Desculpe pela falta de atenção.

**Comment by jackmakiyama** [comment]
Tranquilo @FilipeLinhares vamos corrigindo isso, mas como o propósito da issue foi cumprido vou fecha-la aqui.
