### ISSUE TITLE
Adcionar Twig

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/Wadmin#3]
Mudar esse forma procedural que está, começando adicionando um Template Engine.

**Comment by jackmakiyama** [comment]
@edailton como anda ai?
Pegou o jeito do twig?

**Comment by ghost** [comment]
Opa o básico já entendi, muito legal.

**Comment by jackmakiyama** [comment]
pode crer, quando finalizar o que tem ali faz um PR aqui.
